name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init --force --recursive
    - name: Install dependencies
      run: sudo apt install -y ninja-build llvm-11-dev meson
    - name: Configure
      run: mkdir build; meson -Dbuildtype=debugoptimized build
    - name: Build
      run: ninja -v -C build
    - name: Test
      run: meson test -v -C build
